
services:
  redis:
    image: redis:latest
    container_name: soko-data-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: